#!/bin/bash -eux

# ensure ~/downloads structure
mkdir -p ~/downloads
mkdir -p ~/downloads/blackhole
mkdir -p ~/downloads/movies
mkdir -p ~/downloads/pre-processed-tv
mkdir -p ~/downloads/safe
mkdir -p ~/downloads/torrent
mkdir -p ~/downloads/tv

# ensure ~/rtorrent structure
mkdir -p ~/rtorrent/data/blackhole
mkdir -p ~/rtorrent/data/movies
mkdir -p ~/rtorrent/data/pre-processed-tv
mkdir -p ~/rtorrent/data/safe
mkdir -p ~/rtorrent/data/torrent
mkdir -p ~/rtorrent/data/tv

# ensure ~/.bash_*
cp -f ~/.acorn/profile ~/.bash_profile
cp -f ~/.acorn/aliases ~/.bash_aliases

# ensure rtorrent.rc
mkdir -p ~/.config/rtorrent
cat ~/.acorn/rtorrent | \
  sed -re "s:/home/USERNAME:$HOME:" > \
  ~/.rtorrent.rc

# ensure rutorrent config.php
cd ~/www/*/public_html/rutorrent/conf/users
mkdir -p "$(whoami)"
cp ~/.acorn/rutorrent "$(whoami)/config.php"
