#!/bin/bash -eux

# ensure ~/downloads structure
mkdir -p ~/downloads
mkdir -p ~/downloads/blackhole
mkdir -p ~/downloads/movies
mkdir -p ~/downloads/pre-processed-tv
mkdir -p ~/downloads/safe
mkdir -p ~/downloads/tv
mkdir -p ~/downloads/torrents
mkdir -p ~/downloads/torrents/blackhole
mkdir -p ~/downloads/torrents/movies
mkdir -p ~/downloads/torrents/pre-processed-tv
mkdir -p ~/downloads/torrents/safe
mkdir -p ~/downloads/torrents/tv

# ensure ~/private/rtorrent structure
mkdir -p ~/private/rtorrent/data/blackhole
mkdir -p ~/private/rtorrent/data/movies
mkdir -p ~/private/rtorrent/data/pre-processed-tv
mkdir -p ~/private/rtorrent/data/safe
mkdir -p ~/private/rtorrent/data/tv

# ensure ~/.bash_*
cp -f ~/.acorn/profile ~/.bash_profile
cp -f ~/.acorn/aliases ~/.bash_aliases

# ensure ~/rtorrent symlink exists
ln -sf ~/private/rtorrent ~

# ensure rtorrent version
echo -n '0.9.6_w0.13.6' > ~/private/rtorrent/.version

# ensure rtorrent.rc
cat ~/.acorn/rtorrent | \
  sed -re "s:/home/USERNAME:$HOME:" > \
  ~/.rtorrent.rc

# ensure rutorrent config.php
cd ~/www/*/public_html/rutorrent/conf/users
mkdir -p "$(whoami)"
cp ~/.acorn/rutorrent "$(whoami)/config.php"

# ensure ~/src directory exists
mkdir -p ~/src

# install pip virtualenv
pip install --user virtualenv
~/.local/bin/virtualenv ~/src/pip --system-site-packages

# install sickchill and dependencies
git clone https://github.com/SickChill/SickChill.git ~/SickChill 2>/dev/null || true
cd ~/SickChill
git fetch
git reset --hard origin/master
~/src/pip/bin/pip install --upgrade -r ~/SickChill/requirements/requirements.txt
~/src/pip/bin/pip install --upgrade pyopenssl

# initial sickchill configuration
if [ ! -d ~/.SickChill.tv.shows ]; then
  # boot sickchill to setup initial files
  ~/src/pip/bin/python ~/SickChill/SickBeard.py -d --pidfile="$HOME/SickChill/SickChill.pid"
  pkill -9 -fu "$(whoami)" 'SickChill/SickBeard.py'
  rm -rf ~/SickChill/SickChill.pid && sleep 10

  # generate ~/.SickChill.tv.shows
  mkdir ~/.SickChill.tv.shows
  sed -ri 's|web_port = (.*)|web_port = '"$(shuf -i 10001-32001 -n 1)"'|g' ~/SickChill/config.ini
  sed -ri 's|web_root = (.*)|web_root = /'"$(whoami)"'/sickchill|g' ~/SickChill/config.ini
  sed -ri 's|launch_browser = 1|launch_browser = 0|g' ~/SickChill/config.ini
  sed -ri 's#root_dirs = (.*)#root_dirs = '"$HOME"'/.SickChill.tv.shows#g' ~/SickChill/config.ini
fi
