#!/bin/bash

# Boots SickChill

echo "Booting SickChill..."

~/src/python3/python \
  ~/SickChill/SickChill.py \
  -d --nolaunch \
  --pidfile="$HOME/SickChill/SickChill.pid" \
  --config="$HOME/SickChill/config.ini" \
  --datadir="$HOME/SickChill"

# shellcheck disable=SC2181
if [ $? = 0 ]; then
  port="$(sed -rn 's/(.*)web_port = //p' ~/SickChill/config.ini)"
  echo "http://$(hostname -f):$port/$(whoami)/sickchill"
fi
